AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a new CodeCommit repository on AWS


Parameters:
  RepoName:
    Description: A name for the CodeCommit repository
    Type: String
    Default: DevOpsProjectRepov2

Resources:
  CodeRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: This is a repository for Steve's DevOps project 

Outputs:
  CloneRepoUrlv2:
    Description: The url to clone the repository
    Value: !GetAtt CodeRepo.CloneUrlHttp
    Export:
      Name: CloneRepoUrlv2
  CCRepov2:
    Description: The CodeCommit Reference for CloudFormation
    Value: !GetAtt CodeRepo.Name
    Export:
      Name: CCRepov2